apiVersion: v1
kind: Namespace
metadata:
  name: PLACEHOLDER-NS

---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: PLACEHOLDER-CLUSTERSET
  namespace: PLACEHOLDER-NS
spec:
  clusterSet: PLACEHOLDER-CLUSTERSET

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: PLACEHOLDER-PLACEMENT-NAME
  namespace: PLACEHOLDER-NS
  annotations:
    cluster.open-cluster-management.io/experimental-scheduling-disable: "true"
spec:
  clusterSets:
    - PLACEHOLDER-CLUSTERSET
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: PLACEHOLDER-PREFERRED-CLUSTER
