apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeReplicationClass
metadata:
  name: vrclass-stress
  labels:
    ramendr.openshift.io/replicationid: "PLACEHOLDER"
    ramendr.openshift.io/replication-class: "PLACEHOLDER"
    ramendr.openshift.io/storageid: "PLACEHOLDER"
spec:
  provisioner: block.csi.ibm.com
  parameters:
    replication_policy: np-2-site-async-dr
    replication.storage.openshift.io/replication-secret-name: secret-stress
    replication.storage.openshift.io/replication-secret-namespace: stress
    schedulingInterval: 5m