apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr
  - target:
      kind: ManagedClusterSetBinding
    patch: |-
      - op: replace
        path: /metadata/name
        value: ramen1
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/clusterSet
        value: ramen1
  - target:
      kind: Placement
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-app-placement-1
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/clusterSets/0
        value: ramen1
      - op: replace
        path: /spec/predicates/0/requiredClusterSelector/labelSelector/matchLabels/name
        value: ramen-ocp1
  - target:
      kind: DRPolicy
    patch: |-
      - op: replace
        path: /metadata/name
        value: ramen-policy-1-2-basic-rw-partition
      - op: replace
        path: /spec/drClusters/0
        value: ramen-ocp1
      - op: replace
        path: /spec/drClusters/1
        value: ramen-ocp2
      - op: replace
        path: /spec/replicationClassSelector/matchLabels/ramendr.openshift.io~1replication-class
        value: ibm-block-csi-replication-basic-rw-partition
  - target:
      kind: DRPlacementControl
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-drpc
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/preferredCluster
        value: ramen-ocp1
      - op: replace
        path: /spec/drPolicyRef/name
        value: ramen-policy-1-2-basic-rw-partition
      - op: replace
        path: /spec/placementRef/name
        value: basic-rw-partition-dr-app-placement-1
      - op: replace
        path: /spec/pvcSelector/matchLabels/appname
        value: basic-rw-partition-dr
  - target:
      kind: Application
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-app
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/selector/matchExpressions/0/values/0
        value: basic-rw-partition-dr-app
  - target:
      kind: Subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1git-path
        value: 3-workload/1-subscription-acm/1-basic-rw/partition
      - op: replace
        path: /metadata/labels/app
        value: basic-rw-partition-dr-app
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-sub-1
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/placement/placementRef/name
        value: basic-rw-partition-dr-app-placement-1
