apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-rw
  namespace: basic-rw
type: Opaque
stringData:
  management_address: PLACEHOLDER
  dr_management_address: PLACEHOLDER
  username: superuser
data:
  password: cGFzc3cwcmQ=