apiVersion: ramendr.openshift.io/v1alpha1
kind: DRCluster
metadata:
  name: shirly-ramen-ocp-dr1
  labels:
    cluster.open-cluster-management.io/backup: ramen
spec:
  s3ProfileName: minio-s3-shirly-ramen-ocp-dr1

---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRCluster
metadata:
  name: shirly-ramen-ocp-dr2
  labels:
    cluster.open-cluster-management.io/backup: ramen
spec:
  s3ProfileName: minio-s3-shirly-ramen-ocp-dr2
