apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr
  - target:
      kind: ManagedClusterSetBinding
    patch: |-
      - op: replace
        path: /metadata/name
        value: ramen-shirly
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/clusterSet
        value: ramen-shirly
  - target:
      kind: Placement
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-shirly-app-placement-1
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/clusterSets/0
        value: ramen-shirly
      - op: replace
        path: /spec/predicates/0/requiredClusterSelector/labelSelector/matchLabels/name
        value: shirly-ramen-ocp-dr1
  - target:
      kind: DRPolicy
    patch: |-
      - op: replace
        path: /metadata/name
        value: ramen-policy-shirly-basic-rw-partition
      - op: replace
        path: /spec/drClusters/0
        value: shirly-ramen-ocp-dr1
      - op: replace
        path: /spec/drClusters/1
        value: shirly-ramen-ocp-dr2
      - op: replace
        path: /spec/replicationClassSelector/matchLabels/ramendr.openshift.io~1replication-class
        value: ibm-block-csi-replication-basic-rw-partition
  - target:
      kind: DRPlacementControl
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-shirly-drpc
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/preferredCluster
        value: shirly-ramen-ocp-dr1
      - op: replace
        path: /spec/drPolicyRef/name
        value: ramen-policy-shirly-basic-rw-partition
      - op: replace
        path: /spec/placementRef/name
        value: basic-rw-partition-dr-shirly-app-placement-1
      - op: replace
        path: /spec/pvcSelector/matchLabels/appname
        value: basic-rw-partition-dr
  - target:
      kind: Application
    patch: |-
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-shirly-app
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/selector/matchExpressions/0/values/0
        value: basic-rw-partition-dr-shirly-app
  - target:
      kind: Subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1git-path
        value: 3-workload/1-subscription-acm/1-basic-rw/partition
      - op: replace
        path: /metadata/labels/app
        value: basic-rw-partition-dr-shirly-app
      - op: replace
        path: /metadata/name
        value: basic-rw-partition-dr-shirly-sub-1
      - op: replace
        path: /metadata/namespace
        value: basic-rw-partition-dr
      - op: replace
        path: /spec/placement/placementRef/name
        value: basic-rw-partition-dr-shirly-app-placement-1
