apiVersion: v1
kind: ConfigMap
metadata:
  name: ramen-hub-operator-config
  namespace: openshift-operators
  labels:
    app: ramen-hub
    cluster.open-cluster-management.io/backup: ramen
data:
  ramen_manager_config.yaml: |
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: RamenConfig
    ramenControllerType: dr-hub
    ramenOpsNamespace: openshift-dr-ops
    maxConcurrentReconciles: 50
    retainNamespaceSCCAcrossPeers: true
    volumeUnprotectionEnabled: true
    drClusterOperator:
      catalogSourceName: odf-konflux-4-23
      catalogSourceNamespaceName: openshift-marketplace
      channelName: stable-4.23
      clusterServiceVersionName: odr-cluster-operator.v4.23.0-36.stable
      deploymentAutomationEnabled: true
      namespaceName: openshift-dr-system
      packageName: odr-cluster-operator
      s3SecretDistributionEnabled: true
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      leaseDuration: 0s
      renewDeadline: 0s
      resourceLock: ""
      resourceName: hub.ramendr.openshift.io
      resourceNamespace: ""
      retryPeriod: 0s
    metrics:
      bindAddress: 127.0.0.1:9289
    multiNamespace:
      FeatureEnabled: true
      volsyncSupported: true
    kubeObjectProtection:
      veleroNamespaceName: openshift-adp
    volSync:
      destinationCopyMethod: Direct
    s3StoreProfiles:
      - s3ProfileName: minio-s3-ramen-ocp1
        s3Bucket: ramen-ocp1-bucket
        s3CompatibleEndpoint: http://minio-http-minio-storage.apps.shirly-ramen-ocp-hub-1.xiv.ibm.com
        s3Region: us-east-1
        s3SecretRef:
          name: ramen-s3-secret
          namespace: openshift-operators
      - s3ProfileName: minio-s3-ramen-ocp2
        s3Bucket: ramen-ocp2-bucket
        s3CompatibleEndpoint: http://minio-http-minio-storage.apps.shirly-ramen-ocp-hub-1.xiv.ibm.com
        s3Region: us-east-1
        s3SecretRef:
          name: ramen-s3-secret
          namespace: openshift-operators
      - s3ProfileName: minio-s3-ramen-ocp3
        s3Bucket: ramen-ocp3-bucket
        s3CompatibleEndpoint: http://minio-http-minio-storage.apps.shirly-ramen-ocp-hub-1.xiv.ibm.com
        s3Region: us-east-1
        s3SecretRef:
          name: ramen-s3-secret
          namespace: openshift-operators
      - s3ProfileName: minio-s3-shirly-ramen-ocp-dr1
        s3Bucket: shirly-ramen-ocp-dr1-bucket
        s3CompatibleEndpoint: http://minio-http-minio-storage.apps.shirly-ramen-ocp-hub-1.xiv.ibm.com
        s3Region: us-east-1
        s3SecretRef:
          name: ramen-s3-secret
          namespace: openshift-operators
      - s3ProfileName: minio-s3-shirly-ramen-ocp-dr2
        s3Bucket: shirly-ramen-ocp-dr2-bucket
        s3CompatibleEndpoint: http://minio-http-minio-storage.apps.shirly-ramen-ocp-hub-1.xiv.ibm.com
        s3Region: us-east-1
        s3SecretRef:
          name: ramen-s3-secret
          namespace: openshift-operators
