apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-shared-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app-key: shared-template
  template:
    metadata:
      labels:
        app-key: shared-template
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app-key: shared-template
              topologyKey: kubernetes.io/hostname
      containers:
        - name: busybox
          image: quay.io/nirsof/busybox:stable
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-shared-template