apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Deployment
      name: deploy-vol-2
    patch: |-
      - op: replace
        path: /metadata/name
        value: deploy-vol-2-reader