apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: ramen-policy-1-2-basic-rw-non-partition
spec:
  drClusters:
    - ramen-ocp1
    - ramen-ocp2
  replicationClassSelector:
    matchLabels:
      ramendr.openshift.io/replication-class: ibm-block-csi-replication-basic-rw-non-partition
  schedulingInterval: 5m
