apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: PLACEHOLDER-DRPOLICY-NAME
spec:
  drClusters:
    - PLACEHOLDER-CLUSTER-A
    - PLACEHOLDER-CLUSTER-B
  replicationClassSelector:
    matchLabels:
      ramendr.openshift.io/replication-class: PLACEHOLDER-REPL-CLASS
  schedulingInterval: 5m
