apiVersion: v1
kind: Namespace
metadata:
  name: argocd-basic-rw-partition-dr
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: ramen1
  namespace: openshift-gitops
spec:
  clusterSet: ramen1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: argocd-basic-rw-partition-appset
  namespace: openshift-gitops
  labels:
    cluster.open-cluster-management.io/placement: argocd-basic-rw-partition-appset
  annotations:
    cluster.open-cluster-management.io/experimental-scheduling-disable: "true"
spec:
  numberOfClusters: 1
  clusterSets:
    - ramen1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: ramen-ocp1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-basic-rw-partition-appset
  namespace: openshift-gitops
  labels:
    cluster.open-cluster-management.io/placement: argocd-basic-rw-partition-appset
data:
  apiVersion: "cluster.open-cluster-management.io/v1beta1"
  kind: "placementdecisions"
  statusListKey: "decisions"
  matchKey: "clusterName"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocm-placement-consumer
  namespace: openshift-gitops
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["placementdecisions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocm-placement-consumer
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocm-placement-consumer
subjects:
  - kind: ServiceAccount
    namespace: openshift-gitops
    name: openshift-gitops-applicationset-controller
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argocd-basic-rw-partition-gitops-cluster
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: argocd-basic-rw-partition-appset
    namespace: openshift-gitops
