apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: basic-rw-partition-dr-drpc
  namespace: basic-rw-partition-dr
spec:
  preferredCluster: ramen-ocp1
  drPolicyRef:
    name: ramen-policy-1-2-basic-rw-partition
  placementRef:
    kind: Placement
    name: basic-rw-partition-dr-app-placement-1
  pvcSelector:
    matchLabels:
      appname: basic-rw-partition-dr
