apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scale-19
  labels:
    appname: scale-non-partition-dr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-scale-2-non-partition-dr
  resources:
    requests:
      storage: 40Gi
