apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scale-47
  labels:
    appname: scale-non-partition-dr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-scale-4-non-partition-dr
  resources:
    requests:
      storage: 40Gi
