apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-basic-rw-non-partition-dr
  - target:
      kind: ManagedClusterSetBinding
    patch: |-
      - op: replace
        path: /metadata/name
        value: ramen1
      - op: replace
        path: /spec/clusterSet
        value: ramen1
  - target:
      kind: Placement
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-basic-rw-non-partition-appset
      - op: replace
        path: /metadata/labels/cluster.open-cluster-management.io~1placement
        value: argocd-basic-rw-non-partition-appset
      - op: replace
        path: /spec/clusterSets/0
        value: ramen1
      - op: replace
        path: /spec/predicates/0/requiredClusterSelector/labelSelector/matchLabels/name
        value: ramen-ocp1
  - target:
      kind: ConfigMap
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-basic-rw-non-partition-appset
      - op: replace
        path: /metadata/labels/cluster.open-cluster-management.io~1placement
        value: argocd-basic-rw-non-partition-appset
  - target:
      kind: GitOpsCluster
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-basic-rw-non-partition-gitops-cluster
      - op: replace
        path: /spec/placementRef/name
        value: argocd-basic-rw-non-partition-appset
  - target:
      kind: DRPolicy
    patch: |-
      - op: replace
        path: /metadata/name
        value: ramen-policy-1-2-argocd-basic-rw-non-partition
      - op: replace
        path: /spec/drClusters/0
        value: ramen-ocp1
      - op: replace
        path: /spec/drClusters/1
        value: ramen-ocp2
      - op: replace
        path: /spec/replicationClassSelector/matchLabels/ramendr.openshift.io~1replication-class
        value: ibm-block-csi-replication-argocd-basic-rw-non-partition
  - target:
      kind: DRPlacementControl
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-basic-rw-non-partition-dr-drpc
      - op: replace
        path: /spec/preferredCluster
        value: ramen-ocp1
      - op: replace
        path: /spec/drPolicyRef/name
        value: ramen-policy-1-2-argocd-basic-rw-non-partition
      - op: replace
        path: /spec/placementRef/name
        value: argocd-basic-rw-non-partition-appset
      - op: replace
        path: /spec/pvcSelector/matchLabels/appname
        value: argocd-basic-rw-non-partition-dr
  - target:
      kind: ApplicationSet
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-basic-rw-non-partition-appset
      - op: replace
        path: /spec/generators/0/clusterDecisionResource/configMapRef
        value: argocd-basic-rw-non-partition-appset
      - op: replace
        path: /spec/generators/0/clusterDecisionResource/labelSelector/matchLabels/cluster.open-cluster-management.io~1placement
        value: argocd-basic-rw-non-partition-appset
      - op: replace
        path: /spec/template/metadata/name
        value: 'argocd-basic-rw-non-partition-{{name}}'
      - op: replace
        path: /spec/template/spec/source/path
        value: 3-workload/2-argocd/1-basic-rw/non-partition
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: argocd-basic-rw-non-partition-dr
