apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: scale-non-partition-dr-drpc
  namespace: scale-non-partition-dr
spec:
  preferredCluster: ramen-ocp1
  drPolicyRef:
    name: ramen-policy-1-2-scale-non-partition
  placementRef:
    kind: Placement
    name: scale-non-partition-dr-app-placement-1
  pvcSelector:
    matchLabels:
      appname: scale-non-partition-dr
