apiVersion: v1
kind: Secret
metadata:
  name: secret-argocd-basic-rw
  namespace: argocd-basic-rw
type: Opaque
stringData:
  management_address: PLACEHOLDER
  # dr_management_address: PLACEHOLDER
  username: superuser
data:
  password: cGFzc3cwcmQ=
