apiVersion: v1
kind: Secret
metadata:
  name: secret-scale
  namespace: scale
type: Opaque
stringData:
  management_address: PLACEHOLDER
  # dr_management_address: PLACEHOLDER
  username: superuser
data:
  password: cGFzc3cwcmQ=