apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-scale-1
  labels:
    ramendr.openshift.io/storageid: "PLACEHOLDER"
    ramendr.openshift.io/replicationid: "PLACEHOLDER"
provisioner: block.csi.ibm.com
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  pool: CSI_Parent_Pool
  virt_snap_func: "true"
  volume_group: parth-ramen-scale-1
  volume_name_prefix: vol-rmn-scale-1
  csi.storage.k8s.io/provisioner-secret-name: secret-scale
  csi.storage.k8s.io/provisioner-secret-namespace: scale
  csi.storage.k8s.io/controller-publish-secret-name: secret-scale
  csi.storage.k8s.io/controller-publish-secret-namespace: scale
  csi.storage.k8s.io/fstype: ext4