apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-template
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: STORAGE_CLASS_NAME
  resources:
    requests:
      storage: 1Gi