apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: PLACEHOLDER-DRPC-NAME
  namespace: PLACEHOLDER-NS
spec:
  preferredCluster: PLACEHOLDER-PREFERRED-CLUSTER
  drPolicyRef:
    name: PLACEHOLDER-DRPOLICY-NAME
  placementRef:
    kind: Placement
    name: PLACEHOLDER-APPSET-NAME
    namespace: openshift-gitops
  pvcSelector:
    matchLabels:
      appname: PLACEHOLDER-NS
