apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: PLACEHOLDER-APPSET-NAME
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: PLACEHOLDER-APPSET-NAME
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: PLACEHOLDER-APPSET-NAME
        requeueAfterSeconds: 30
  template:
    metadata:
      name: 'PLACEHOLDER-APPSET-NAME-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/parthraaj/ramen-dr-test
        targetRevision: main
        path: PLACEHOLDER-GIT-PATH
      destination:
        server: '{{server}}'
        namespace: PLACEHOLDER-NS
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
