apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-scale-64-reader
  labels:
    appname: scale-non-partition-dr
spec:
  replicas: 1
  selector:
    matchLabels:
      app-key: scale-64
  template:
    metadata:
      labels:
        app-key: scale-64
        appname: scale-non-partition-dr
        scale-test: spread
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              scale-test: spread
      containers:
        - name: busybox
          image: quay.io/nirsof/busybox:stable
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-scale-64
