apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scale-1
  labels:
    appname: scale-partition-dr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-scale-1-partition-dr
  resources:
    requests:
      storage: 40Gi
