apiVersion: ramendr.openshift.io/v1alpha1
kind: DRCluster
metadata:
  name: ramen-ocp1
  labels:
    cluster.open-cluster-management.io/backup: ramen
spec:
  s3ProfileName: minio-s3-ramen-ocp1

---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRCluster
metadata:
  name: ramen-ocp2
  labels:
    cluster.open-cluster-management.io/backup: ramen
spec:
  s3ProfileName: minio-s3-ramen-ocp2
