apiVersion: v1
kind: ConfigMap
metadata:
  name: ramen-hub-operator-config
  namespace: openshift-operators
  labels:
    app: ramen-hub
    cluster.open-cluster-management.io/backup: ramen
data:
  ramen_manager_config.yaml: |
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: RamenConfig
    ramenControllerType: dr-hub
    ramenOpsNamespace: openshift-dr-ops
    multiNamespace:
      FeatureEnabled: true
      volsyncSupported: true
    kubeObjectProtection:
      veleroNamespaceName: openshift-adp
    s3StoreProfiles:
      - s3ProfileName: minio-s3-ramen-ocp1
        s3Bucket: ramen-ocp1-bucket
        s3CompatibleEndpoint: http://minio-http-minio-storage.apps.shirly-ramen-ocp-hub-1.xiv.ibm.com
        s3Region: us-east-1
        s3SecretRef:
          name: ramen-s3-secret
          namespace: openshift-operators
      - s3ProfileName: minio-s3-ramen-ocp2
        s3Bucket: ramen-ocp2-bucket
        s3CompatibleEndpoint: http://minio-http-minio-storage.apps.shirly-ramen-ocp-hub-1.xiv.ibm.com
        s3Region: us-east-1
        s3SecretRef:
          name: ramen-s3-secret
          namespace: openshift-operators
