apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Namespace
      name: stress
    patch: |-
      - op: replace
        path: /metadata/name
        value: stress-partition-dr
  - target:
      kind: Secret
      name: secret-stress
    patch: |-
      - op: replace
        path: /metadata/name
        value: secret-stress-partition-dr
      - op: replace
        path: /metadata/namespace
        value: stress-partition-dr
      - op: add
        path: /stringData/partition_name
        value: Ramen-DR-Partition-Parth
  - target:
      kind: StorageClass
      name: sc-stress-a
    patch: |-
      - op: replace
        path: /metadata/name
        value: sc-stress-a-partition-dr
      - op: replace
        path: /metadata/labels/ramendr.openshift.io~1replicationid
        value: ibm-block-csi-replication-stress-partition
      - op: replace
        path: /parameters/volume_group
        value: parth-ramen-stress-a-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1provisioner-secret-name
        value: secret-stress-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1provisioner-secret-namespace
        value: stress-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1controller-publish-secret-name
        value: secret-stress-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1controller-publish-secret-namespace
        value: stress-partition-dr
  - target:
      kind: StorageClass
      name: sc-stress-b
    patch: |-
      - op: replace
        path: /metadata/name
        value: sc-stress-b-partition-dr
      - op: replace
        path: /metadata/labels/ramendr.openshift.io~1replicationid
        value: ibm-block-csi-replication-stress-partition
      - op: replace
        path: /parameters/volume_group
        value: parth-ramen-stress-b-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1provisioner-secret-name
        value: secret-stress-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1provisioner-secret-namespace
        value: stress-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1controller-publish-secret-name
        value: secret-stress-partition-dr
      - op: replace
        path: /parameters/csi.storage.k8s.io~1controller-publish-secret-namespace
        value: stress-partition-dr
  - target:
      kind: VolumeReplicationClass
      name: vrclass-stress
    patch: |-
      - op: replace
        path: /metadata/name
        value: vrclass-stress-partition-dr
      - op: replace
        path: /metadata/labels/ramendr.openshift.io~1replicationid
        value: ibm-block-csi-replication-stress-partition
      - op: replace
        path: /metadata/labels/ramendr.openshift.io~1replication-class
        value: ibm-block-csi-replication-stress-partition
      - op: replace
        path: /spec/parameters/replication_policy
        value: partition-async-dr
      - op: replace
        path: /spec/parameters/replication.storage.openshift.io~1replication-secret-name
        value: secret-stress-partition-dr
      - op: replace
        path: /spec/parameters/replication.storage.openshift.io~1replication-secret-namespace
        value: stress-partition-dr