apiVersion: v1
kind: Namespace
metadata:
  name: argocd-basic-rw-non-partition-dr
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: ramen1
  namespace: openshift-gitops
spec:
  clusterSet: ramen1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: argocd-basic-rw-non-partition-appset
  namespace: openshift-gitops
  labels:
    cluster.open-cluster-management.io/placement: argocd-basic-rw-non-partition-appset
  annotations:
    cluster.open-cluster-management.io/experimental-scheduling-disable: "true"
spec:
  numberOfClusters: 1
  clusterSets:
    - ramen1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: ramen-ocp1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-basic-rw-non-partition-appset
  namespace: openshift-gitops
  labels:
    cluster.open-cluster-management.io/placement: argocd-basic-rw-non-partition-appset
data:
  apiVersion: "cluster.open-cluster-management.io/v1beta1"
  kind: "placementdecisions"
  statusListKey: "decisions"
  matchKey: "clusterName"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocm-placement-consumer
  namespace: openshift-gitops
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["placementdecisions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocm-placement-consumer
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocm-placement-consumer
subjects:
  - kind: ServiceAccount
    namespace: openshift-gitops
    name: openshift-gitops-applicationset-controller
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argocd-basic-rw-non-partition-gitops-cluster
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: argocd-basic-rw-non-partition-appset
    namespace: openshift-gitops
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPolicy
metadata:
  name: ramen-policy-1-2-argocd-basic-rw-non-partition
spec:
  drClusters:
    - ramen-ocp1
    - ramen-ocp2
  replicationClassSelector:
    matchLabels:
      ramendr.openshift.io/replication-class: ibm-block-csi-replication-argocd-basic-rw-non-partition
  schedulingInterval: 5m
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: argocd-basic-rw-non-partition-dr-drpc
  namespace: argocd-basic-rw-non-partition-dr
spec:
  preferredCluster: ramen-ocp1
  drPolicyRef:
    name: ramen-policy-1-2-argocd-basic-rw-non-partition
  placementRef:
    kind: Placement
    name: argocd-basic-rw-non-partition-appset
  pvcSelector:
    matchLabels:
      appname: argocd-basic-rw-non-partition-dr
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-basic-rw-non-partition-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: argocd-basic-rw-non-partition-appset
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: argocd-basic-rw-non-partition-appset
        requeueAfterSeconds: 30
  template:
    metadata:
      name: 'argocd-basic-rw-non-partition-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/parthraaj/ramen-dr-test
        targetRevision: main
        path: 3-workload/2-argocd/1-basic-rw/non-partition
      destination:
        server: '{{server}}'
        namespace: argocd-basic-rw-non-partition-dr
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
