apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: argocd-basic-rw-non-partition-dr-drpc
  namespace: argocd-basic-rw-non-partition-dr
spec:
  preferredCluster: ramen-ocp1
  drPolicyRef:
    name: ramen-policy-1-2-argocd-basic-rw-non-partition
  placementRef:
    kind: Placement
    name: argocd-basic-rw-non-partition-appset
  pvcSelector:
    matchLabels:
      appname: argocd-basic-rw-non-partition-dr
